aws_config_ini: null
db_connection_str: '**********'
db_name: dev_db
inbox_bucket: inbox
outbox_bucket: outbox
permanent_bucket: permanent
s3_access_key_id: test
s3_endpoint_url: http://localstack:4566
s3_secret_access_key: '**********'
s3_session_token: null
service_name: internal_file_registry
