aws_config_ini: null
db_connection_str: '**********'
db_name: dev_db
file_deleted_event_topic: internal_file_registry
file_deleted_event_type: file_deleted
file_registered_event_topic: internal_file_registry
file_registered_event_type: file_registered
file_staged_event_topic: internal_file_registry
file_staged_event_type: file_staged_for_download
files_to_delete_topic: file_deletions
files_to_delete_type: file_deletion_requested
files_to_register_topic: file_interrogation
files_to_register_type: file_interrogation_success
files_to_stage_topic: file_downloads
files_to_stage_type: file_stage_requested
kafka_servers:
- kafka:9092
outbox_bucket: outbox
permanent_bucket: permanent
s3_access_key_id: test
s3_endpoint_url: http://localstack:4566
s3_secret_access_key: '**********'
s3_session_token: null
service_instance_id: '1'
service_name: internal_file_registry
staging_bucket: staging
