#!/bin/bash
# install service in dev container

cd /workspace


# install in edit mode
# use-feature way of installing packages
# install with testing dependencies
pip install \
    --use-feature=in-tree-build \
    -e \
    ".[all]"

# install pre-commit hooks to git:
pre-commit install

# Check if the database has been initialized and if not initialize it
cd db_migration
alembic -c alembic.ini upgrade head
