[project]
name = "ifrs"
version = "1.2.0"
description = "Internal-File-Registry-Service - This service acts as a registry for the internal location and representation of files."
dependencies = [
    "ghga-event-schemas==1.0.0",
    "ghga-service-commons>=2.0.0",
    "hexkit[mongodb,s3,akafka]>=2.0.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/internal-file-registry-service"

[project.scripts]
ifrs = "ifrs.__main__:run_forever"
